version: '3.7'

services:





  react:
    container_name: digimon_react
    image: digimon_react
    build:
      context: .
      dockerfile: ./dockerfile.react
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - digimon-network

networks:
  digimon-network:

