version: '3.7'

services:
  mysql:
    container_name: Digimon_mysql
    build:
      context: ./api
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - digimon-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: Digimon_app
    build:
      context: ./api
      dockerfile: ./dockerfile.app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - digimon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  react:
    container_name: Digimon_react
    build:
      context: ./digimon_react
      dockerfile: ./dockerfile.react
    environment:
      NODE_ENV: production
    ports:
      - 3006:3006
    networks:
      - digimon-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3006 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  digimon-network:
