version: '3.7'

services:
  mysql:
    container_name: Digimon_mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - digimon-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: digimon-app
    build:
      context: .
      dockerfile: ./dockerfile.app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - digimon-network

networks:
  digimon-network:

